creation_rules:
  - path_regex: .*\.yaml$
    encrypted_regex: '^(data|stringData)$'
    # contains public key which is used to encrypt data
    age: 'age1mpdxp9av4z8qu96wp7c55fzzumpmmsen5365slrfs08gmzf06qyq38tjfl'
